src/MusicPlayer/urls.py
from django.urls import path

from . import views


app_name = "App"

urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('register/', views.sign_up, name='register'),

    path('music/', views.index, name='index'),
    path('music/<str:username>/', views.personal_music_view, name='personal_music'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MusicPlayer.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/MusicPlayer/models.py
from django.db import models
from django.urls import reverse
from config import settings
from django.contrib.auth.models import User


class Song(models.Model):
    artist= models.CharField(max_length=200)
    image= models.ImageField(default=settings.STATIC_ROOT 
                             + 'imgs/user_default_img.avif')
    audio_file = models.FileField()
    genres = models.CharField(max_length=200, null=True, blank=True)
    listeners = models.ManyToManyField(User, blank=True)
    title= models.CharField(default='default name', max_length=200, blank=True)
    

    def __str__(self):
        return self.title
    
    # def _format_title(cls, title):
    #     for ch in title:
    #         if ch == 


    

class Playlist(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(default=settings.STATIC_ROOT 
                              + 'imgs/user_default_img.avif')
    owner = models.ForeignKey(User, models.CASCADE)
    song = models.ManyToManyField(Song)

    def __str__(self) -> str:
        return self.title

src/MusicPlayer/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, 
                               widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

src/MusicPlayer/views.py
from typing import Union

from django.http import HttpResponse, HttpRequest, Http404
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet

from .models import Song
from .forms import RegisterForm, LoginForm


@login_required
def personal_music_view(request: HttpRequest, username: str):
    if request.method == 'POST':
        change_song_status = request.POST.get('change_song_status')
        print(change_song_status)
        song_id = request.POST.get('song_id')
        print(song_id)

        if song_id:
            if change_song_status == 'add':
                __add_song(request, song_id)
            elif change_song_status == 'remove':
                __remove_song(request, song_id)
            else:
                raise Http404
        else:
            raise Http404
        return redirect(request.path)

    if request.method == 'GET':
        if request.user.username == username:
            songs = Song.objects.filter(listeners__id=request.user.id)
            songs = __get_filtered_songs(request, 'q', songs)
            paginator= Paginator(songs, 10)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)

            context={"page_obj": page_obj, 'username': username}
            return render(request,"MusicPlayer/personal_music_list.html",context)
        else:
            return HttpResponse("You cannot access this page")
    

def index(request: HttpRequest):
    if request.method == 'POST':
        change_song_status = request.POST.get('change_song_status')
        song_id = request.POST.get('song_id')

        if song_id:
            if change_song_status == 'add':
                __add_song(request, song_id)
            elif change_song_status == 'remove':
                __remove_song(request, song_id)
            else:
                raise Http404
        else:
            raise Http404
        return redirect(request.path)
        
    if request.method == 'GET':
        songs = __get_filtered_songs(request, 'q')
        
        paginator = Paginator(songs, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {'page_obj': page_obj}
        return render(request, 'MusicPlayer/common_music_list.html', context)

@login_required
def __add_song(request, song_id):
    if request.method == 'POST':
        # uniqueness validation 
        song = Song.objects.get(id=song_id)
        song.listeners.add(request.user)
        return redirect('/music/' + request.user.username)
    else:
        return HttpResponse('You did GET request but POST request is required')


@login_required
def __remove_song(request, song_id):
    if request.method == 'POST':
        # uniqueness validation 
        song = Song.objects.get(id=song_id)
        song.listeners.remove(request.user)
        return redirect('/music/' + request.user.username)
    else:
        return HttpResponse('You did GET request but POST request is required')


def __get_filtered_songs(request: HttpRequest, 
                         search_arg: str, 
                         given_songs: QuerySet=None) -> Union[QuerySet, None]:
    '''Returns songs filtered by the search argument among all songs in db, or among given_songs if provided'''
    q = request.GET.get(search_arg, '')

    if given_songs is None:
        songs = Song.objects.all()
    else:
        songs = given_songs
    if q:
        songs = songs.filter(title__startswith=q)
    return songs
    

def sign_up(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'MusicPlayer/register.html', {'form': form})
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, 'You have signed up successfully')
            login(request, user)
            return redirect('App:index')
        else:
            return render(request, 'MusicPlayer/register.html', {'form': form})
        
def sign_in(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'MusicPlayer/login.html', {'form': form})
    
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, 'You have signed in successfully')
                return redirect('App:index')

        messages.error(request, 'This user doesn\'t exist or data are invalid')
        return render(request, 'MusicPlayer/login.html', {'form': form})
    
def sign_out(request):
    logout(request)
    messages.error(request, 'You have been logged out')
    return redirect('App:index')

src/MusicPlayer/templates/MusicPlayer/common_music_list.html
{% extends 'MusicPlayer/music_list_base.html' %}

{% block info %}
<p>All Music</p>
{% endblock info %}

{% block content %}
<div class="music-list">
    {% for song in page_obj %}
        {% include 'components/song_component.html' %}
    {% endfor %}
</div>
{% endblock content %}

src/MusicPlayer/templates/MusicPlayer/index.html
{% extends 'base.html' %}
{% block content %}
<div class="welcome-page">
    
</div>
{% endblock %}

src/MusicPlayer/templates/MusicPlayer/login.html
{% block content %}
<div class="login-form">
    <form action="" method="POST">
        {% csrf_token %}
        <h3>Sign In</h3>
        {{form.as_p}}
        <input type="submit" value="Log In">
    </form>
</div>
{% endblock content %}

src/MusicPlayer/templates/MusicPlayer/music_list_base.html
{% extends 'base.html' %}

{% block info %}
{% endblock info %}

{% block content %}

{% endblock content %}

src/MusicPlayer/templates/MusicPlayer/old_music_list.html
  {% extends 'base.html' %}
  {% block content %}
  {% load static %}
  <!-- partial:index.partial.html -->
  <html>
   <head>
    <meta charset="utf-8"/>
    <title>
     Flat music player
    </title>
   </head>
   <body>
    <div class="contain">
     <div class="container">
      <div class="music-player">
        {% for item in page_obj %}
       <div class="cover">
        <img alt="" src="{{item.image.url}}"/>
       </div>
       <div class="titre">
        <h3>
         {{item.artist}}
        </h3>
        <h1>
         {{item.title}}
        </h1>
       </div>
       <center><a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}"><i class="fa fa-step-backward fa-2x"></i></a> &nbsp; &nbsp; &nbsp; <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }} {% endif %}"><i class="fa fa-step-forward fa-2x"></i></a></center>
       <div class="lecteur">
        <audio class="fc-media" style="width: 100%;">
         <source src="{% if item.audio_file %}{{item.audio_file.url}} {% else %} {{item.audio_link}} {% endif %}" type="audio/mp3"/>
        </audio>
       </div>
       {% endfor %}
      </div>
     </div>
    </div>
   </body>
  </html>
  <!-- partial -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js">
  </script>
  <script src="{% static './script.js' %}">
  </script>
{% endblock content %}

src/MusicPlayer/templates/MusicPlayer/personal_music_list.html
{% extends 'MusicPlayer/music_list_base.html' %}

{% block info %}
<div class="info">
    asddfds
    {% if request.user == username %}
        <p>Your music</p>
    {% else %}
        <p>{{username}}'s music</p>
    {% endif %}
</div>
{% endblock info %}

{% block content %}
<div class="music-list">
    {% for song in page_obj %}
        {% include 'components/song_component.html' %}
    {% endfor %}
</div>
{% endblock content %}

src/MusicPlayer/templates/MusicPlayer/register.html
{% block content %}
<div class="register-form">
    <form method="POST" novalidate>
        {% csrf_token %}
        <h2>Sign Up</h2>
        {{form.as_p}}
        <input type="submit" value="Register">
    </form>
</div>
{% endblock content %}

src/MusicPlayer/templates/components/song_component.html
<div class="song-{{song.id}}">
    <p>{{song.audio_file.name}}</p>
    <audio controls>
    <source src="http://127.0.0.1:8000{{song.audio_file.url}}" type="audio/mpeg">
    error
    </audio>
    {% if request.user not in song.listeners.all %}
    <form action="{{request.path}}" method="POST">
        {% csrf_token %}
        <input type='submit' name='example' value="+"/>
        <input type="hidden" name="song_id" value="{{song.id}}">
        <input type="hidden" name="change_song_status" value="add">
    </form>
    {% else %}
    <form action="{{request.path}}" method="POST">
        {% csrf_token %}
        <input type='submit' name='example' value="-"/>
        <input type="hidden" name="song_id" value="{{song.id}}">
        <input type="hidden" name="change_song_status" value="remove">
    </form>
    {% endif %}
</div>

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   {% block title %}{% endblock %}
  </title>
  {% block links %}{% endblock %}
  <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelementplayer.min.css" rel="stylesheet"/>
  <link href="{% static './style.css' %}" rel="stylesheet"/>
   
 </head>
 <body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    
    <script>
      let audioNL = document.querySelectorAll('audio');
      let audio = Array.apply(null, audioNL);

      audio.forEach(t => {
         t.volume = 0.3
         let index = audio.indexOf(t);

         t.addEventListener('play', () => {
            audio.forEach(subT => {
                  subT !== audio[index] ?
                  (subT.pause(), subT.currentTime = 0) : 
                  subT.play()
            })
         })
         t.addEventListener('ended', () => {
            t.currentTime = 0;
            index !== audio.length - 1 ?
               audio[index + 1].play() :
               audio[0].play
         
         })
      });
      

      
   </script>  
 </body>
</html>

src/templates/navbar.html
<div class="navbar">
    {% if request.user.is_authenticated %}
        <div class="logout">
            <a href="{% url 'App:logout' %}">Log Out</a>
        </div>
        {% if request.path == '/music/' %}
        <div>
            <a href="{% url 'App:personal_music' username=request.user.username %}">to your music</a>
        </div>
        {% elif request.path == '/music/'|add:request.user.username|add:'/' %}
        <div>
            <a href="{% url 'App:index' %}">to all music</a>
        </div>
        {% endif %}
    {% else %}
        <div class="login">
            <a href="{% url 'App:login' %}">Log In</a>
        </div>
    {% endif %}
        <div class="search">
            <form action="" method="GET">
                <input type="text" name="q" id="">
            </form>
        </div>
</div>